### ISSUE TITLE
Prepare previews for documentation and community views

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#285]
**Description**

After we introduce tabs in documentation section in website TWs have a problem with correct preparation of markdown for that feature, so(for my opinion) the best solution would be create previews of documentation and community views.

**Reasons**

Making TWs life easier 😄

**Comment by derberg** [comment]
TWs and other content providers input is must have here, what is most important for them? local or browser experience, where they have the biggest challenges? tabs, links or images. We tried it in previous projects and at the end, the online editor was not enough while local was not easiest

**Comment by klaudiagrz** [comment]
From my observations, lately we've had a problem with tabs - they didn't display correctly and only then we've found out that additional spaces were needed. Tabs are generally not a problem since we can see a preview in GitHub, but the spaces are quite unpredictable.

The perfect example is any numbered list with steps and commands. When attaching a codeblock with commands, I never know how many spaces are needed to have commands nicely indented under the steps. Sometimes they are nicely indented on local but then on website/console they look totally different. This is the situation I have in mind:
![situation](https://user-images.githubusercontent.com/35192450/57444987-ab197300-7251-11e9-9037-8012c60580c6.png)

I remember I've had some troubles with indenting commands under the steps as the content displayed nicely locally but differently on website.

I'm not sure whether this is what you've asked for, but this came into my mind when you asked for our challenges with displaying content on UI :D

**Comment by magicmatatjahu** [comment]
Task is changed and purpose of it is preparing views for documentation preview and community preview only. At the moment separate subdomain for live editing md files in unnecessary.

**Comment by derberg** [comment]
Doesn't work, some examples:

- https://github.com/kyma-project/kyma/pull/6179 - preview got generated even though the readme was edited that is not displayed in Kyma docs
- https://github.com/kyma-project/kyma/pull/6180 - preview failed event though is needed
- and other examples where in fact preview is not needed but fail shows up instead of a message that preview will not be generated as is not needed
