### ISSUE TITLE
Hi! Appreciate you using rooks! I have a small suggestion to give.

### ISSUE THREAD

**Issue by imbhargav5** [kyma-project/website#438]
**Description**

Hi! I am the creator the rooks project. I was going through the dependent network and I found your project. It's not a bug report but I have a suggestion to give.
Rooks is a combination of multiple hooks. If you only need useTimeout consider `@rooks/use-timeout` instead of the entire `rooks` package to save bundle size. So basically you would install `@rooks/use-timeout` instead of `rooks` package in your app. :)

https://github.com/kyma-project/website/blob/95fde888fee6b9b0541522be85776d15c160e9c0/src/common/state/usePopup.ts#L3

**Expected result**

`import useTimeout from '@rooks/use-timeout'`

**Actual result**

`import {useTimeout} from 'rooks'`

**Comment by magicmatatjahu** [comment]
@imbhargav5 HI! I wouldn't think that once someone created such an issue :D Thanks you for your suggestion, but probably using `rooks` instead of `@rooks/use-timeout` for only one of hooks in our project doesn't matter because we use `gatsby` for creating static site, so react compiler carries out all optimization operations, including tree-shaking. 

However, thank you once again. I will create PR with `fixing` that :)

**Comment by imbhargav5** [comment]
@magicmatatjahu Awesome. I don't remember if rooks v1 supports tree shaking as much as v3. Since a lot of improvements came around v3. Also `use-timeout` was improved a bit recently so consider upgrading. ;)

**Comment by magicmatatjahu** [comment]
Resolved by https://github.com/kyma-project/website/pull/440 @imbhargav5 Thanks again! :)
