### ISSUE TITLE
Digital Lights

### ISSUE THREAD

**Issue by malkoto1** [kyma-project/website#496]
**websiteUrl:**
https://lights.digital/

**url:**
N/A

**logo:**
![Digital_Lights_Logo_Small_Sun](https://user-images.githubusercontent.com/1436515/69713287-f53e4500-110c-11ea-8eb3-4ab8c309fec5.png)

**content:**
Kyma provides us with the necessary tools to evolve our customers' existing SAP CX solutions in a flexible way and with minimum risk.

**Comment by derberg** [comment]
@malkoto1 thanks a lot for the info. We will process it as soon as possible

**Comment by derberg** [comment]
@malkoto1 you are already on the landing page, soon will also be in the readme of Kyma repo.
FYI we also accept a guest blog posts on https://kyma-project.io/blog in case you would like to describe in more details what is your use case, what you build on Kyma and why it makes sense to do it with Kyma instead of different solutions

**Comment by derberg** [comment]
The process is pretty simple, fork website repo and make a PR with new post that should be located here https://github.com/kyma-project/website/tree/master/content/blog-posts

**Comment by aerfio** [comment]
And now in main Kyma readme.md too! :tada:
