### ISSUE TITLE
Render preview of yaml files (or other files with code) in the website

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/website#657]
**Description**

Provide a way to enable rendering of yaml files used in the documentation. Assuming you have such snipped in the documentation:
```
kubectl apply -f https://raw.githubusercontent.com/kyma-project/kyma/master/docs/getting-started/assets/orders-service-api-rule.yaml
```
it should be possible to copy the command to the clipboard and display the content of the yaml file. 

**Reasons**
People do not like to apply blindly files without knowing the content. The content brings also educational value. 

**Attachments**
The issue is part of https://github.com/kyma-project/kyma/issues/10216
Related PR: https://github.com/kyma-project/kyma/issues/10050

**Comment by aerfio** [comment]
After investigation I've come to conclusion that website is unfortunately not suited to such kind of task. The problem is that we're not able to read yaml files in browser (we do that in nodejs), which is currently not allowed in our architecture. Developing such a solution is of course possible, but would take too much time than a "very quick task", so we've decided not to implement it, at least for now

**Comment by kwiatekus** [comment]
We will not focus on that at the moment
